// <auto-generated />
using Harris.net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Harris.net.Migrations
{
    [DbContext(typeof(HarrisDbContext))]
    [Migration("20210619170459_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Harris.net.Models.BusinessContact", b =>
                {
                    b.Property<int>("BusinessContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessContactAddr1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessContactAddr2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessContactCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessContactFName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessContactLName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessContactPostcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessTel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessContactID");

                    b.ToTable("BusinessContacts");
                });

            modelBuilder.Entity("Harris.net.Models.PersonalContact", b =>
                {
                    b.Property<int>("PersonalContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersonalContactAddr1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalContactAddr2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalContactCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalContactFName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalContactLName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalContactPostcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalTel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalContactID");

                    b.ToTable("PersonalContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
